# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CanCurveDialog
                                 A QGIS plugin
 Creating depth-damage functions
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-04-24
        git sha              : $Format:%H$
        copyright            : (C) 2024 by NRCan
        email                : heather.mcgrath@canada.ca
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os, datetime, sys
import pandas as pd
import numpy as np

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

 
from qgis.core import Qgis, QgsLogger, QgsMessageLog

from hp.basic import convert_to_number
from hp.qt import (
        DialogQtBasic, get_formLayout_data, get_gridLayout_data, get_tabelWidget_data
        )

from .parameters import (
    building_meta_dtypes, drf_db_default_fp,home_dir
    )

from .parameters_ui import building_details_options_d


#===============================================================================
# helpers-------
#===============================================================================
class plugLogger(object): 
    """pythonic logging interface"""
    
    log_tabnm = 'CanCurve' # qgis logging panel tab name
    
    log_nm = 'cc' #logger name
    
    def __init__(self, 
                 iface,
                 statusQlab=None,                 
                 parent=None,
                 log_nm = None,
                 debug_logger=None,
                 ):
        """
        
        params
        ---------
        debug_logger: python logging class
            workaround to capture QgsLogger
        """
        
        self.iface=iface
        self.statusQlab = statusQlab
        self.parent=parent
        self.debug_logger=debug_logger
        
        if  log_nm is None: #normal calls
            self.log_nm = '%s.%s'%(self.log_nm, self.parent.__class__.__name__)
        else: #getChild calls
            self.log_nm = log_nm
        
        
    def getChild(self, new_childnm):
        
        if hasattr(self.parent, 'logger'):
            log_nm = '%s.%s'%(self.parent.logger.log_nm, new_childnm)
        else:
            log_nm = new_childnm
        
        #build a new logger
        child_log = plugLogger(self.parent, 
                           statusQlab=self.statusQlab,
                           log_nm=log_nm,
                           debug_logger=self.debug_logger)
        

        
        return child_log
    
    def info(self, msg):
        self._loghlp(msg, Qgis.Info, push=False, status=True)


    def debug(self, msg):
        self._loghlp(msg, -1, push=False, status=False)
        
        if not self.debug_logger is None: 
            self.debug_logger.debug(msg)
 
    def warning(self, msg):
        self._loghlp(msg, Qgis.Warning, push=False)

    def push(self, msg):
        self._loghlp(msg, Qgis.Info, push=True)

    def error(self, msg):
        """similar behavior to raising a QError.. but without throwing the execption"""
        self._loghlp(msg, Qgis.Critical, push=True)
        
    def _loghlp(self, #helper function for generalized logging
                msg_raw, qlevel, 
                push=False, #treat as a push message on Qgis' bar
                status=False, #whether to send to the status widget
                ):
        """
        QgsMessageLog writes to the message panel
            optionally, users can enable file logging
            this file logger 
        """

        #=======================================================================
        # send message based on qlevel
        #=======================================================================
        msgDebug = '%s    %s: %s'%(datetime.datetime.now().strftime('%d-%H.%M.%S'), self.log_nm,  msg_raw)
        
        if qlevel < 0: #file logger only            
            QgsLogger.debug('D_%s'%msgDebug)            
            push, status = False, False #should never trip
            
        else:#console logger
            msg = '%s:   %s'%(self.log_nm, msg_raw)
            QgsMessageLog.logMessage(msg, self.log_tabnm, level=qlevel)
            QgsLogger.debug('%i_%s'%(qlevel, msgDebug)) #also send to file
            
        #Qgis bar
        if push:
            try:
                self.iface.messageBar().pushMessage(self.log_tabnm, msg_raw, level=qlevel)
            except:
                QgsLogger.debug('failed to push to interface') #used for standalone tests
        
        #Optional widget
        if status or push:
            if not self.statusQlab is None:
                self.statusQlab.setText(msg_raw)
    
        
        
        
        
        
        




#===============================================================================
# Main Dialog----------
#===============================================================================
#append the path (resources_rc workaround)
sys.path.append(os.path.dirname(__file__))

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'cc_bldgs_dialog.ui'), resource_suffix='')





class BldgsDialog(QtWidgets.QDialog, FORM_CLASS, DialogQtBasic):
    def __init__(self, 
                 parent=None, #not sure what this is supposed to be... 
                 iface=None,
                 debug_logger=None, #testing only
                 ):
        """Constructor."""
        super(BldgsDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        
        
        self.iface=iface
        
        #setup logger
        self.logger = plugLogger(self.iface, parent=self, statusQlab=self.progressText,
                                 debug_logger=debug_logger)
        
        self.connect_slots()
        
        self.logger.debug('CanCurveDialog init finish')
        #self.logger.info('this woriks?')
        
 
        
    def connect_slots(self):
        """
        using the cointaier (dict) self.launch_actions to store functions
            that should be called once the dialog is launched
            see self.launch()
        """
        log = self.logger.getChild('connect_slots')
        log.debug('connecting slots')
 
        
        
        #=======================================================================
        # general----------------
        #=======================================================================
        self.close_pushButton.clicked.connect(self.close) 
        self.cancel_pushButton.clicked.connect(self.action_cancel_process)
        #=======================================================================
        # Tab: 02 Building Details-------
        #=======================================================================
        
        #=======================================================================
        # populate ui
        #=======================================================================
        #populate form options from parameters
        for k,v in building_details_options_d.items():
            #append empty
            options_l = v
            #retrieve the combo box matching the name
            log.debug(f'setting \'{k}\':{options_l}')
            comboBox = self._get_child(f'{k}_ComboBox', childType=QtWidgets.QComboBox)
            comboBox.addItems([str(e) for e in options_l])
            comboBox.setCurrentIndex(-1)
            
        #add the current date to the LineEdit
        self.dateCurveCreatedLineEdit.setText(datetime.datetime.now().strftime('%Y %m %d %H:%M:%S'))
        
        #username
        self.createdByLineEdit.setText(os.getlogin())
        
        
        #=======================================================================
        # Tab: 03 Data Input-----
        #=======================================================================
        
        #=======================================================================
        # populate ui
        #=======================================================================
        self.lineEdit_di_drf_db_fp.setText(drf_db_default_fp)
        self.lineEdit_wdir.setText(home_dir)
        
        
        #=======================================================================
        # Tab: 04 Create Curve---------
        #=======================================================================
        self.pushButton_Tcc_run.clicked.connect(self.action_Tcc_run)
        
        
        
        
        
    def action_Tcc_run(self):
        """pushButton_Tcc_run
        
        TODO: implement QgsTask
        
        """
        log = self.logger.getChild('action_Tcc_run')
        log.push(f'start')
        
        #=======================================================================
        # #retrieve info from UI----------
        #=======================================================================
        
        ci_fp = self.lineEdit_di_cifp.text()
        drf_db_fp = self.lineEdit_di_drf_db_fp.text()
        
        out_dir = self.lineEdit_wdir.text()
        #curve_name = self.lineEdit_di_curveName.text() in settings_d
        bldg_meta = self.get_building_details(logger=log)
        fixed_costs_d = self.get_fixed_costs(logger=log)
        settings_d = self.get_settings(logger=log)
        
        
        #=======================================================================
        # run actions-------
        #=======================================================================
        from .core import c00_setup_project, c01_join_drf, c02_group_story, c03_export
        
        c00_setup_project(
            ci_fp, drf_db_fp=drf_db_fp, bldg_meta=bldg_meta, fixed_costs_d=fixed_costs_d,
            settings_d=settings_d,

            
            )
        
    def action_cancel_process(self):
        """handle user cancel request
        
        may need to implement QgsTask for this to work
        
        cancel_pushButton
        
        
        """
        # 1. Set a flag to signal cancellation 
        self.process_should_cancel = True     
 
    
        # 3. Optionally provide feedback to the user and 
        self.logger.warning('user requested \'Cancel\'')
        #    (e.g., disable the cancel button, show a progress bar)
        
    def _get_building_details(self,
                              logger=None):
        """retrieve dataa from Building Details tab"""
        if logger is None: logger = self.logger
        log = logger.getChild('_get_building_details')
        
        #=======================================================================
        # extract from layouts----------
        #=======================================================================
        #=======================================================================
        # #general  building details
        #=======================================================================
        bldg_meta_d = get_formLayout_data(self.formLayout_t02_01)
        
        #=======================================================================
        # #size age materials (grid layout)
        #======================================================================= 
        bldg_meta_d.update(get_gridLayout_data(self.gridLayout_t02_02))
        
        #=======================================================================
        # location costs
        #=======================================================================
        bldg_meta_d.update(get_formLayout_data(self.formLayout_t02_03))
        
        #=======================================================================
        # misc
        #=======================================================================
        bldg_meta_d.update(get_formLayout_data(self.formLayout_t02_04))
        
        #=======================================================================
        # fixes----
        #=======================================================================
        for k,v in bldg_meta_d.copy().items():
            new_v=None
            if isinstance(v, str):
                if '\u00B2' in v:
                    new_v = v.replace('\u00B2', '2')
                elif v=='':
                    new_v = np.nan
                else:
                    new_v = convert_to_number(v) 
                    
                    
            if not new_v is None:
                bldg_meta_d[k] = new_v
                
        
        #=======================================================================
        # #check all of the keys are present
        #=======================================================================
        """
        bldg_meta_d['locationCityTownRegionLineEdit']
        for k,v in bldg_meta_d.items():
            print(f'{k}\n    {v} ({type(v)})')
        """
        
        log.debug(f'collected {len(bldg_meta_d)} entries from \'Building Details\' tab')
        building_meta_dtypes
        
        return bldg_meta_d
        
    def _get_fixed_costs(self, logger=None):
        """retireve fixed costs from 'Data Input' tab"""
        df_raw =  get_tabelWidget_data(self.tableWidget_di_fixedCosts)
        
        return df_raw.astype(float).set_index(df_raw.columns[0]).iloc[:, 0].to_dict()
 
 
        
    def _get_settings(self, logger=None):
        """retrieve project settings from Data Input  tab"""
        return {
            'curve_name':self.lineEdit_di_curveName.text(),
            'scale_m2':self.radioButton_di_rcvm2.isChecked(), #retrieve from radio buttons
            }


            

        
        
        
        
 
        

        
